#Vector operations QUIZ_0
1.Write a function add_vectors(u, v) that takes two lists of numbers of the same length,
  and returns a new list containing the sums of the corresponding elements of each.

In [7]:
import numpy as np 
def add_vectors (a,b):
    c=np.add(a,b)
    return c
a=[10,3,6]
b=[2,1,59]    
add_vectors(a,b)    

array([12,  4, 65])

In [8]:
d=np.add([1, 0], [1, 1])
d

array([2, 1])

2.Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the scalar multiple of v by s.

In [17]:
def scalar_mult(s,v):
    a=np.multiply(s,v)
    return a
s=7
v=[3, 0, 5, 11, 2]
scalar_mult(s,v)    

array([21,  0, 35, 77, 14])

In [10]:
s_m=np.multiply(3,[1,4,5])
s_m

array([ 3, 12, 15])

3.Write a function dot_product(u, v) that takes two lists of numbers of the same length,
  and returns the sum of the products of the corresponding elements of each (the dot_product.

In [27]:
def dot_product(u,v):
    d_p=np.dot(u,v)
    return d_p
u=[[2, 0],[1,2]]
v=[[1, 5],[1,2]]
dot_product(u,v)    


array([[ 2, 10],
       [ 3,  9]])

In [81]:
dp=np.dot([1, 2, 1],[1, 4, 3])
dp

12


#Matrices
#Create a new module or use the Jupyter notebook provided and add the following function,
which returns a copy of nested lists of numbers such that the lists are not aliases:
4. Copy Matrix

In [30]:
#adenumerate in numpy
a = np.array([[1, 2,8], [3, 4,10]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(0, 2) 8
(1, 0) 3
(1, 1) 4
(1, 2) 10


In [38]:
#copy matrix
def copy_matrix(matrix):
    matrix=[[1,2],[3,4]]
    print(matrix)
copy_matrix(matrix)

[[1, 2], [3, 4]]


5.add_row in matrix

In [47]:
def add_row(matrix):
    a=[[0,1],[1,1]]
    b=[[0,0]]
    c=a+b
    return c
add_row(matrix)    


[[0, 1], [1, 1], [0, 0]]

6.add_column in matrix

In [72]:
def add_column(matrix):
    a=[[0,1],[1,1]]
    c=[[0],[1]]
    a_d=np.append(a,c, axis=1)
    return a_d
add_column(matrix)    


array([[0, 1, 0],
       [1, 1, 1]])

8.Add matrices m1 and m2

In [73]:
import numpy as np 
def add_matrices (m1,m2):
    c=np.add(m1,m2)
    return c
m1=[[10,3,6],[1,2,4]]
m2=[[2,1,59],[3,4,6]]   
add_vectors(m1,m2)   

array([[12,  4, 65],
       [ 4,  6, 10]])

9.Add scalar matrix to vector

In [74]:
def scalar_mult(s,m):
    a=np.multiply(s,m)
    return a
s=10
m=[[1, 2], [3, 4]]
scalar_mult(s,m) 

array([[10, 20],
       [30, 40]])

10. Matrix Multiplication

In [75]:
def dot_product(m1,m2):
    d_p=np.dot(m1,m2)
    return d_p
m1=[[1, 2], [3,  4]]
m2=[[5, 6], [7, 8]]
dot_product(m1,m2)  

array([[19, 22],
       [43, 50]])

In [78]:
import numpy as np

a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
b= np.array([10, 20, 30])

print("A =", a)

print("b =", b)

print("Ab =",np.dot(a,b))

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
b = [10 20 30]
Ab = [140 320 500]


11.Transpose matrix

In [80]:
def transpose(m):
    m=[[3, 4, 6], [1, 5, 9]]
    m_t=np.transpose(m)
    return m_t
transpose(m)    

array([[3, 1],
       [4, 5],
       [6, 9]])