In [1]:
import numpy as np

Linear Algebra Quiz 3

In [2]:
A=[[3,1,2],[-5,4,1],[0,3,-8]]
B=[[0,5,-1],[3,2,-1],[10,0.5,4]]
C=[0.6,-15,2,5,98]
D=[[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]]
# matrix multiplication using numpy

In [3]:
#sucesseful because 1*5 and 5*3 resultant mantrix is 1*3
E=np.dot(C,D)
E

array([-102.8,  255.2,  595.6])

In [ ]:
# The matrix is not defined because of its rows and colomns
F=np.matmul(D,C)

Inverse of a matrix

In [13]:
A=np.array([[3,1,2],[-5,4,1],[0,3,-8]])
A


array([[ 3,  1,  2],
       [-5,  4,  1],
       [ 0,  3, -8]])

In [10]:
np.linalg.inv(A)

array([[ 0.2       , -0.08      ,  0.04      ],
       [ 0.22857143,  0.13714286,  0.07428571],
       [ 0.08571429,  0.05142857, -0.09714286]])